S8 Code refactor (1)
SwEnt-Project-G18/SwEntApp pull request #182
Opened 2024-05-17 20:26 UTC by DanThePol

- Made Repositories static objects and updated viewmodels to reflect this change
- Removed useless static elements from constructors (like Firebase.firestore)
- Simplified other function signatures when possible (e.g. from a bunch of fields from Event to just passing the event as a parameter)
- Converted all the Spacers with hardcoded size I found to screen size dependent Spacers
- Moved certain code snippets to private helper functions and added/redefined some enums for code legibility (for instance in Events.kt)
- Moved certain helper functions into the model folder (for example getCountries went from ui.authscreens.register.RegisterNameCountryPhone.kt to model.authentication.SignInState.kt)
- Added missing documentation

This is a massive PR, I should've broken this down into smaller PRs. More code refactoring to come, I'm still not done with the main.java.com.github.se.gomeet folder.

2024-05-17 21:32 UTC, eloibressaud commented on app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/ManageInvites.kt
Way clearer using enum and separate helper functions.

2024-05-17 21:36 UTC, eloibressaud commented on app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/Events.kt
Again this is way clearer, well done.

2024-05-17 21:50 UTC, eloibressaud commented on app/src/main/java/com/github/se/gomeet/ui/theme/Theme.kt
I believe onBackground = Color.Black should stay even if not really necessary for clarity reason.

2024-05-17 22:40 UTC, eloibressaud requested changes
This should have been multiple PRs as it touches on multiple parts of the code in various ways, making it hard to follow.

It however greatly improve on code readability and is an overall great improvement. As it passes all the automated tests and holds up to basic manual testing i believe it should be merged once the small issue with Theme.kt has been solved.

2024-05-18 09:44 UTC, DanThePol commented on app/src/main/java/com/github/se/gomeet/ui/theme/Theme.kt
Well spotted, I just added it back!

2024-05-18 09:56 UTC, eloibressaud approved these changes
Changes solved the previous issue

2024-05-18 14:11 UTC, merged